CREATE DATABASE IF NOT EXISTS test;
USE test;
DROP TABLE IF EXISTS DBUSER;
CREATE TABLE DBUSER (
  USER_ID       INT (5)    NOT NULL,
  USERNAME      VARCHAR (20)  NOT NULL,
  CREATED_BY    VARCHAR (20)  NOT NULL,
  CREATED_DATE  DATE          NOT NULL,
  PRIMARY KEY ( USER_ID )
);